ascendente = int(input())

if ascendente <100 or 999:
    print("numero invalido")


















#(ex4.py) Um número natural é chamado de ascendente se cada um dos seus algarismos é estrita-
#mente maior do que qualquer um dos algarismos colocados à sua esquerda. Por exemplo, o número
#358 (3 < 5 < 8) é ascendente. Faça um programa que leia um número inteiro n no intervalo
#[100, 999] e diga se n é ou não ascendente. Além disso, caso o número esteja fora do intervalo
#[100, 999], exiba uma mensagem de erro. Neste exercício, você deve utilizar operadores matemá-
#ticos, ou seja, você não pode considerar o valor como um string. Pense em como separar cada
#dígito do número inteiro lido









